// ─── Shared style objects for the Onboarding flow ─────────────
// All values are kept pixel-perfect from the original Onboarding.jsx.

const s = {
  wrapper: {
    minHeight: '100dvh',
    position: 'relative',
    overflow: 'hidden',
    display: 'flex',
    fontFamily: 'var(--font-body)',
  },
  bgImage: {
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    zIndex: 0,
    transformOrigin: 'center center',
  },
  overlay: {
    position: 'absolute',
    inset: 0,
    background: 'linear-gradient(160deg, rgba(220,245,228,0.50) 0%, rgba(180,225,195,0.42) 100%)',
    zIndex: 1,
  },
  inner: {
    position: 'relative',
    zIndex: 2,
    width: '100%',
    maxWidth: '480px',
    margin: '0 auto',
    display: 'flex',
    flexDirection: 'column',
    minHeight: '100dvh',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '16px 20px 8px',
  },
  backBtn: {
    width: '40px', height: '40px',
    borderRadius: '12px',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    cursor: 'pointer',
    border: 'none',
  },
  stepCounter: {
    fontSize: '0.8125rem',
    fontWeight: 600,
    color: 'var(--color-text-muted)',
    letterSpacing: '0.3px',
  },
  progressTrack: {
    height: '3px',
    background: 'rgba(255,255,255,0.35)',
    margin: '8px 20px 0',
    borderRadius: '4px',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    background: 'var(--color-accent)',
    borderRadius: '4px',
    transition: 'width 450ms cubic-bezier(0.16,1,0.3,1)',
  },
  content: {
    flex: 1,
    overflowY: 'auto',
    padding: '24px 20px',
  },
  stepContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
  },
  stepTitle: {
    fontSize: 'clamp(1.4rem, 4vw, 1.7rem)',
    fontWeight: 700,
    color: 'var(--color-text)',
    letterSpacing: '-0.4px',
    lineHeight: 1.2,
  },
  stepSubtitle: {
    fontSize: '0.9rem',
    color: 'var(--color-text-muted)',
    marginTop: '-16px',
  },
  fields: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  fieldGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  label: {
    fontSize: '0.8125rem',
    fontWeight: 600,
    color: 'var(--color-text-muted)',
    letterSpacing: '0.2px',
  },
  input: {
    width: '100%',
    padding: '13px 16px',
    background: 'rgba(255,255,255,0.60)',
    backdropFilter: 'blur(8px)',
    WebkitBackdropFilter: 'blur(8px)',
    border: '1px solid rgba(255,255,255,0.70)',
    borderRadius: 'var(--radius-md)',
    color: 'var(--color-text)',
    fontSize: '1rem',
    fontFamily: 'var(--font-body)',
    transition: 'border-color var(--transition), box-shadow var(--transition), background var(--transition)',
  },
  optionRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
  },
  chip: {
    padding: '8px 18px',
    borderRadius: '999px',
    fontSize: '0.875rem',
    fontFamily: 'var(--font-body)',
    cursor: 'pointer',
    transition: 'all 200ms cubic-bezier(0.16,1,0.3,1)',
    whiteSpace: 'nowrap',
  },
  cardGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '10px',
  },
  goalCard: {
    padding: '14px',
    borderRadius: 'var(--radius-md)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    cursor: 'pointer',
    position: 'relative',
    transition: 'all 200ms cubic-bezier(0.16,1,0.3,1)',
    textAlign: 'left',
  },
  goalCheck: {
    position: 'absolute',
    top: '10px', right: '10px',
    width: '18px', height: '18px',
    background: 'var(--color-accent)',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  summaryCard: {
    background: 'rgba(255,255,255,0.55)',
    backdropFilter: 'blur(16px)',
    WebkitBackdropFilter: 'blur(16px)',
    border: '1px solid rgba(255,255,255,0.65)',
    borderRadius: 'var(--radius-lg)',
    overflow: 'hidden',
    boxShadow: 'var(--shadow-md)',
  },
  summaryRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '12px 16px',
  },
  summaryLabel: {
    fontSize: '0.875rem',
    color: 'var(--color-text-muted)',
  },
  summaryValue: {
    fontSize: '0.875rem',
    fontWeight: 600,
    color: 'var(--color-text)',
    textTransform: 'capitalize',
  },
  aiNote: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '12px',
    background: 'rgba(58,158,95,0.10)',
    border: '1px solid rgba(58,158,95,0.25)',
    borderRadius: 'var(--radius-md)',
    padding: '14px',
    backdropFilter: 'blur(8px)',
    WebkitBackdropFilter: 'blur(8px)',
  },
  footer: {
    padding: '16px 20px',
    paddingBottom: 'calc(16px + env(safe-area-inset-bottom))',
    borderTop: '1px solid rgba(255,255,255,0.30)',
  },
  nextBtn: {
    width: '100%',
    padding: '15px',
    background: 'var(--color-accent)',
    color: '#ffffff',
    border: 'none',
    borderRadius: 'var(--radius-md)',
    fontSize: '1rem',
    fontWeight: 700,
    fontFamily: 'var(--font-body)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    transition: 'background var(--transition), transform var(--transition), box-shadow var(--transition)',
    letterSpacing: '0.2px',
  },
  hintText: {
    textAlign: 'center',
    fontSize: '0.75rem',
    color: 'var(--color-text-faint)',
    marginTop: '8px',
  },
  loadingOverlay: {
    position: 'fixed',
    inset: 0,
    zIndex: 50,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'rgba(220,245,228,0.45)',
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
  },
  loadingCard: {
    borderRadius: 'var(--radius-xl)',
    padding: '40px 36px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
    maxWidth: '320px',
    width: '90%',
  },
  loadingSentence: {
    fontSize: '1rem',
    fontWeight: 600,
    color: 'var(--color-text)',
    fontFamily: 'var(--font-body)',
    lineHeight: 1.5,
    minHeight: '48px',
    transition: 'opacity 400ms ease, transform 400ms ease',
    marginBottom: '12px',
  },
  loadingHint: {
    fontSize: '0.8rem',
    color: 'var(--color-text-faint)',
    fontFamily: 'var(--font-body)',
  },
}

export default s
