# Generated by Django 6.0.3 on 2026-04-02 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('diet_type', models.CharField(choices=[('jain', 'Jain'), ('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian')], default='veg', max_length=10)),
                ('calories', models.FloatField()),
                ('protein_g', models.FloatField(default=0)),
                ('carbs_g', models.FloatField(default=0)),
                ('fats_g', models.FloatField(default=0)),
                ('fiber_g', models.FloatField(default=0)),
                ('serving_size_g', models.FloatField(default=100)),
                ('is_fasting_friendly', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('target_calories', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start_date'],
                'unique_together': {('user', 'week_start_date')},
            },
        ),
        migrations.CreateModel(
            name='DayMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('on_track', 'On Track'), ('adjusted', 'Adjusted'), ('regenerated', 'Regenerated')], default='on_track', max_length=15)),
                ('total_calories', models.FloatField(default=0)),
                ('total_protein_g', models.FloatField(default=0)),
                ('total_carbs_g', models.FloatField(default=0)),
                ('total_fats_g', models.FloatField(default=0)),
                ('weekly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_meals', to='meals.weeklyplan')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('weekly_plan', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='MealSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=15)),
                ('quantity_g', models.FloatField(default=100)),
                ('calories', models.FloatField(default=0)),
                ('protein_g', models.FloatField(default=0)),
                ('carbs_g', models.FloatField(default=0)),
                ('fats_g', models.FloatField(default=0)),
                ('day_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_slots', to='meals.daymeal')),
                ('food_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meals.fooditem')),
            ],
            options={
                'unique_together': {('day_meal', 'slot')},
            },
        ),
    ]
