# Generated by Django 6.0.3 on 2026-04-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daymeal',
            name='day_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daymeal',
            name='is_fasting_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='is_jain_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='serving_unit',
            field=models.CharField(default='serving', max_length=50),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='plan_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
