# Generated by Django 6.0.3 on 2026-04-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_daymeal_day_notes_daymeal_is_fasting_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='ingredients',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
