# Generated by Django 6.0.3 on 2026-04-12 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_fooditem_ingredients'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='daymeal',
            unique_together={('weekly_plan', 'date')},
        ),
    ]
