# Generated by Django 6.0.3 on 2026-06-23 16:14

from django.conf import settings
from django.db import migrations, models


def create_indexes_if_not_exist(apps, schema_editor):
    """Create indexes only if they don't already exist"""
    if schema_editor.connection.vendor != 'postgresql':
        return
    
    with schema_editor.connection.cursor() as cursor:
        # List of indexes to create
        indexes = [
            ('meals_daymeal', 'meals_dayme_date_9a626f_idx', '("date")'),
            ('meals_daymeal', 'meals_dayme_weekly__c019cb_idx', '("weekly_plan_id", "date")'),
            ('meals_daymeal', 'meals_dayme_status_805ac9_idx', '("status")'),
            ('meals_weeklyplan', 'meals_weekl_user_id_411fbf_idx', '("user_id", "week_start_date")'),
            ('meals_weeklyplan', 'meals_weekl_user_id_eaf75b_idx', '("user_id", "week_end_date")'),
            ('meals_weeklyplan', 'meals_weekl_week_st_ba244a_idx', '("week_start_date", "week_end_date")'),
        ]
        
        for table, index_name, columns in indexes:
            cursor.execute(
                f"CREATE INDEX IF NOT EXISTS {index_name} ON {table} {columns}"
            )


def drop_indexes(apps, schema_editor):
    """Drop indexes on migration rollback"""
    if schema_editor.connection.vendor != 'postgresql':
        return
    
    with schema_editor.connection.cursor() as cursor:
        indexes = [
            'meals_dayme_date_9a626f_idx',
            'meals_dayme_weekly__c019cb_idx',
            'meals_dayme_status_805ac9_idx',
            'meals_weekl_user_id_411fbf_idx',
            'meals_weekl_user_id_eaf75b_idx',
            'meals_weekl_week_st_ba244a_idx',
        ]
        
        for index_name in indexes:
            cursor.execute(f"DROP INDEX IF EXISTS {index_name}")


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_fooditem_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(create_indexes_if_not_exist, drop_indexes),
    ]
