# Generated by Django 6.0.3 on 2026-08-29 07:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='daymeal',
            index=models.Index(fields=['date'], name='meals_dayme_date_9a626f_idx'),
        ),
        migrations.AddIndex(
            model_name='daymeal',
            index=models.Index(fields=['weekly_plan', 'date'], name='meals_dayme_weekly__c019cb_idx'),
        ),
        migrations.AddIndex(
            model_name='daymeal',
            index=models.Index(fields=['status'], name='meals_dayme_status_805ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyplan',
            index=models.Index(fields=['user', 'week_start_date'], name='meals_weekl_user_id_411fbf_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyplan',
            index=models.Index(fields=['user', 'week_end_date'], name='meals_weekl_user_id_eaf75b_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyplan',
            index=models.Index(fields=['week_start_date', 'week_end_date'], name='meals_weekl_week_st_ba244a_idx'),
        ),
    ]
