# Generated by Django 6.0.3 on 2026-04-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='week_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
