# Generated by Django 6.0.3 on 2026-04-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_trainingplan_week_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytraining',
            name='day_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='exercise',
            name='reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='sets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
