# Generated by Django 6.0.3 on 2026-04-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_daytraining_day_notes_exercise_reps_exercise_sets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('flexibility', 'Flexibility'), ('bodyweight', 'Bodyweight')], max_length=50),
        ),
    ]
