# Generated by Django 6.0.3 on 2026-06-23 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_alter_exercise_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='daytraining',
            index=models.Index(fields=['date'], name='training_da_date_54da2a_idx'),
        ),
        migrations.AddIndex(
            model_name='daytraining',
            index=models.Index(fields=['training_plan', 'date'], name='training_da_trainin_50bd95_idx'),
        ),
        migrations.AddIndex(
            model_name='daytraining',
            index=models.Index(fields=['is_rest_day'], name='training_da_is_rest_9d6675_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingplan',
            index=models.Index(fields=['user', 'week_start_date'], name='training_tr_user_id_259e44_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingplan',
            index=models.Index(fields=['user', 'week_end_date'], name='training_tr_user_id_f42b56_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingplan',
            index=models.Index(fields=['week_start_date', 'week_end_date'], name='training_tr_week_st_b31d28_idx'),
        ),
    ]
