# Generated by Django 6.0.3 on 2026-04-02 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheatMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_method', models.CharField(choices=[('image', 'Image Upload'), ('manual', 'Manual Text Entry')], max_length=10)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('meal_date', models.DateField()),
                ('food_name', models.CharField(blank=True, max_length=200)),
                ('quantity_description', models.CharField(blank=True, max_length=300)),
                ('ai_estimated_calories', models.FloatField(blank=True, null=True)),
                ('user_edited_calories', models.FloatField(blank=True, null=True)),
                ('size', models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('ai_raw_response', models.JSONField(blank=True, null=True)),
                ('adjustment_days', models.PositiveIntegerField(default=0)),
                ('adjustment_applied', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheat_meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='CheatMealImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cheat_meals/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cheat_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cheat_meals.cheatmeal')),
            ],
        ),
    ]
