# Generated by Django 6.0.3 on 2026-04-12 10:23

import cheat_meals.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheat_meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheatmealimage',
            name='image',
            field=models.ImageField(upload_to='cheat_meals/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), cheat_meals.models.validate_image_size]),
        ),
    ]
