# Generated by Django 6.0.3 on 2026-04-02 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('target_weight_kg', models.FloatField(blank=True, null=True)),
                ('health_time_minutes', models.PositiveIntegerField(default=60)),
                ('goal', models.CharField(choices=[('muscle_building', 'Muscle Building'), ('fat_loss', 'Fat Loss'), ('weight_loss', 'Weight Loss'), ('maintenance', 'Maintenance')], default='maintenance', max_length=20)),
                ('diet_preference', models.CharField(choices=[('jain', 'Jain'), ('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian')], default='veg', max_length=10)),
                ('beverage_habit', models.CharField(choices=[('none', 'None'), ('tea', 'Tea'), ('coffee', 'Coffee'), ('both', 'Both')], default='none', max_length=10)),
                ('tea_type', models.CharField(blank=True, choices=[('milk', 'Milk Tea'), ('black', 'Black Tea'), ('green', 'Green Tea')], max_length=10, null=True)),
                ('coffee_type', models.CharField(blank=True, choices=[('milk', 'Milk Coffee'), ('black', 'Black Coffee')], max_length=10, null=True)),
                ('morning_beverage', models.CharField(blank=True, max_length=10, null=True)),
                ('evening_beverage', models.CharField(blank=True, max_length=10, null=True)),
                ('is_fasting', models.BooleanField(default=False)),
                ('fasting_days', models.CharField(blank=True, max_length=100, null=True)),
                ('fasting_type', models.CharField(blank=True, max_length=100, null=True)),
                ('has_gym', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.FloatField()),
                ('logged_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
    ]
