# Generated by Django 6.0.3 on 2026-05-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="target_calories",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
