# Generated by Django 6.0.3 on 2026-04-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='needs_refresh',
            field=models.BooleanField(default=False),
        ),
    ]
